server:
  port: 9050

spring:
  application:
    name: user-service
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate.format_sql: true
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@192.168.50.170:1882/WPMS12
    username: WINGSENT5
    password: WINGS_4172

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka

greeting:
  message: Welcome

management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans

